logging:
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config: classpath:logback-slack.xml
  level:
    org.springframework.data.redis: DEBUG
jpa:
  open-in-view: false
  hibernate:
    ddl-auto: create // spring.jpa.ddl-auto 를 통해 설정 가능
  properties:
    hibernate:
      show_sql: true
      format_sql: true
  defer-datasource-initialization: true

spring:
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer




#spring:
#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379


